language: java
jdk:
  - oraclejdk8
install:
  - hg clone https://bitbucket.org/allr/mx
  - wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar
  - mv ecj-4.5.1.jar mx/ecj.jar
  - export JDT=mx/ecj.jar
script:
  - $TEST_COMMAND
env:
  - TEST_COMMAND='mx/mx pylint'
  - TEST_COMMAND='mx/mx checkoverlap'
  - TEST_COMMAND='mx/mx canonicalizeprojects'
  - TEST_COMMAND='mx/mx build -p --warning-as-error && mx/mx unittest'
  - TEST_COMMAND='mx/mx build -p --warning-as-error --force-javac && mx/mx unittest'
  - TEST_COMMAND='mx/mx checkstyle'
  - TEST_COMMAND='mx/mx findbugs'
  - TEST_COMMAND='mx/mx build -p --force-javac && mx/mx javadoc --unified'
  


